### PR TITLE
Support Swift versions 3.1 through 4.1

### PR DESCRIPTION
**Pull request by djones6**
Changes to allow PathKit to build on Swift 3.1, 4.0 and 4.1:
- Support Swift 3.1 through 4.1 by reintroducing the Swift 3 format Package.swift from 0.8.0, and renaming the Swift 4 format to `Package@swift-4.swift`
- Remove deprecation warnings for String API changes in Swift 4 - similar to #42 / #45, but guarded to maintain compatibility with Swift 3
- Address compilation error on Linux + Swift 4.1 due to https://github.com/apple/swift-corelibs-foundation/pull/1223
- Update `lastComponentWithoutExtension` test for Linux + Swift 4.1
- Add travis matrix for testing with both Swift 3.1.1 and 4.0 snapshots (I didn't add a 4.1 dev snapshot, but this would be straightforward)

### CODE REVIEW

**Comment by ianpartridge** [comment]
LGTM - @kylef?

**Comment by ianpartridge** [comment]
@kylef ping.. we need Swift 4.1 support here otherwise we'll have to do a temporary fork :-(

**Comment by keith** [comment]
We've just release 0.9.1 which includes https://github.com/kylef/PathKit/pull/48. This has all the same fixes here, except we opted to not support 3.1. Thanks for submitting this though!
