### ISSUE TITLE
PathKit wont compile with swift 3.0 snapshot DEVELOPMENT-SNAPSHOT-2016-05-03-a

### ISSUE THREAD

**Issue by paulatwilson** [kylef/PathKit#16]
/vagrant/www/Packages/PathKit-0.6.3/Sources/PathKit.swift:579:21: warning: @noescape is now an attribute on a parameter type, instead of on the parameter itself
  public func chdir(@noescape closure: () throws -> ()) rethrows {
                    ^~~~~~~~~
                                       @noescape
/vagrant/www/Packages/PathKit-0.6.3/Sources/PathKit.swift:68:21: error: value of type 'Index' (aka 'String.CharacterView.Index') has no member 'distance'
      let index = p.startIndex.distance( to: p.startIndex.successor())
                  ~~^~~~~~~~~~ ~~~~~~~~
/vagrant/www/Packages/PathKit-0.6.3/Sources/PathKit.swift:196:41: error: value of type 'NSFileManager' has no member 'destinationOfSymbolicLinkAtPath'
      let symlinkDestination = try Path.fileManager.destinationOfSymbolicLinkAtPath(path)
                                   ~~~~~^~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/vagrant/www/Packages/PathKit-0.6.3/Sources/PathKit.swift:277:19: error: value of type 'NSFileManager' has no member 'fileExistsAtPath'
      return Path.fileManager.fileExistsAtPath(self.path)
             ~~~~~^~~~~~~~~~~ ~~~~~~~~~~~~~~~~
/vagrant/www/Packages/PathKit-0.6.3/Sources/PathKit.swift:298:18: error: value of type 'NSFileManager' has no member 'fileExistsAtPath'
      guard Path.fileManager.fileExistsAtPath(normalize().path, isDirectory: &directory) else {
            ~~~~~^~~~~~~~~~~ ~~~~~~~~~~~~~~~~
/vagrant/www/Packages/PathKit-0.6.3/Sources/PathKit.swift:325:18: error: value of type 'NSFileManager' has no member 'fileExistsAtPath'
      guard Path.fileManager.fileExistsAtPath(normalize().path, isDirectory: &directory) else {
            ~~~~~^~~~~~~~~~~ ~~~~~~~~~~~~~~~~
/vagrant/www/Packages/PathKit-0.6.3/Sources/PathKit.swift:348:26: error: value of type 'NSFileManager' has no member 'destinationOfSymbolicLinkAtPath'
        let _ = try Path.fileManager.destinationOfSymbolicLinkAtPath(path)
                    ~~~~~^~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/vagrant/www/Packages/PathKit-0.6.3/Sources/PathKit.swift:370:19: error: value of type 'NSFileManager' has no member 'isReadableFileAtPath'
      return Path.fileManager.isReadableFileAtPath(self.path)
             ~~~~~^~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~
/vagrant/www/Packages/PathKit-0.6.3/Sources/PathKit.swift:388:19: error: value of type 'NSFileManager' has no member 'isWritableFileAtPath'
      return Path.fileManager.isWritableFileAtPath(self.path)
             ~~~~~^~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~
/vagrant/www/Packages/PathKit-0.6.3/Sources/PathKit.swift:406:19: error: value of type 'NSFileManager' has no member 'isExecutableFileAtPath'
      return Path.fileManager.isExecutableFileAtPath(self.path)
             ~~~~~^~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~
/vagrant/www/Packages/PathKit-0.6.3/Sources/PathKit.swift:424:19: error: value of type 'NSFileManager' has no member 'isDeletableFileAtPath'
      return Path.fileManager.isDeletableFileAtPath(self.path)
             ~~~~~^~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~
/vagrant/www/Packages/PathKit-0.6.3/Sources/PathKit.swift:447:16: error: value of type 'NSFileManager' has no member 'createDirectoryAtPath'
      try Path.fileManager.createDirectoryAtPath(self.path, withIntermediateDirectories: false, attributes: nil)
          ~~~~~^~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~
/vagrant/www/Packages/PathKit-0.6.3/Sources/PathKit.swift:464:16: error: value of type 'NSFileManager' has no member 'createDirectoryAtPath'
      try Path.fileManager.createDirectoryAtPath(self.path, withIntermediateDirectories: true, attributes: nil)
          ~~~~~^~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~
/vagrant/www/Packages/PathKit-0.6.3/Sources/PathKit.swift:481:16: error: value of type 'NSFileManager' has no member 'removeItemAtPath'
      try Path.fileManager.removeItemAtPath(self.path)
          ~~~~~^~~~~~~~~~~ ~~~~~~~~~~~~~~~~
/vagrant/www/Packages/PathKit-0.6.3/Sources/PathKit.swift:498:16: error: value of type 'NSFileManager' has no member 'moveItemAtPath'
      try Path.fileManager.moveItemAtPath(self.path, toPath: destination.path)
          ~~~~~^~~~~~~~~~~ ~~~~~~~~~~~~~~
/vagrant/www/Packages/PathKit-0.6.3/Sources/PathKit.swift:515:16: error: value of type 'NSFileManager' has no member 'copyItemAtPath'
      try Path.fileManager.copyItemAtPath(self.path, toPath: destination.path)
          ~~~~~^~~~~~~~~~~ ~~~~~~~~~~~~~~
/vagrant/www/Packages/PathKit-0.6.3/Sources/PathKit.swift:531:16: error: value of type 'NSFileManager' has no member 'linkItemAtPath'
      try Path.fileManager.linkItemAtPath(self.path, toPath: destination.path)
          ~~~~~^~~~~~~~~~~ ~~~~~~~~~~~~~~
/vagrant/www/Packages/PathKit-0.6.3/Sources/PathKit.swift:547:16: error: value of type 'NSFileManager' has no member 'createSymbolicLinkAtPath'
      try Path.fileManager.createSymbolicLinkAtPath(self.path, withDestinationPath: destination.path)
          ~~~~~^~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~
/vagrant/www/Packages/PathKit-0.6.3/Sources/PathKit.swift:665:18: error: value of type 'NSString' has no member 'substringFromIndex'
      return try NSString(contentsOfFile: path, encoding: encoding).substringFromIndex(0) as String
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~
/vagrant/www/Packages/PathKit-0.6.3/Sources/PathKit.swift:684:11: error: value of type 'NSData' has no member 'writeToFile'
      try data.writeToFile(normalize().path, options: .DataWritingAtomic)
          ^~~~ ~~~~~~~~~~~
/vagrant/www/Packages/PathKit-0.6.3/Sources/PathKit.swift:708:11: error: value of type 'NSString' has no member 'writeToFile'
      try NSString(string: string).writeToFile(normalize().path, atomically: true, encoding: encoding)
          ^~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~
/vagrant/www/Packages/PathKit-0.6.3/Sources/PathKit.swift:739:23: error: value of type 'NSFileManager' has no member 'contentsOfDirectoryAtPath'
      return try Path.fileManager.contentsOfDirectoryAtPath(path).map {
                 ~~~~~^~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~
/vagrant/www/Packages/PathKit-0.6.3/Sources/PathKit.swift:763:23: error: value of type 'NSFileManager' has no member 'subpathsOfDirectoryAtPath'
      return try Path.fileManager.subpathsOfDirectoryAtPath(path).map {
                 ~~~~~^~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~
/vagrant/www/Packages/PathKit-0.6.3/Sources/PathKit.swift:804:59: error: value of optional type 'UnsafeMutablePointer<Int8>?' not unwrapped; did you mean to use '!' or '?'?
          if let path = String(validatingUTF8: gt.gl_pathv[index]) {
                                                          ^
                                                                 !
/vagrant/www/Packages/PathKit-0.6.3/Sources/PathKit.swift:818:22: error: missing argument label 'pattern:' in call
    return Path.glob((self + pattern).description)
                     ^
                     pattern: 
/vagrant/www/Packages/PathKit-0.6.3/Sources/PathKit.swift:840:41: error: value of type 'NSFileManager' has no member 'enumeratorAtPath'
        self.directoryEnumerator = Path.fileManager.enumeratorAtPath(path.path)!
                                   ~~~~~^~~~~~~~~~~ ~~~~~~~~~~~~~~~~

**Comment by kylef** [comment]
Swift 3 support is already tracked in #13 so going to close this duplicate issue.
