### PR TITLE
Update Spectre to 0.10.0 for Xcode 12.5

### PR DESCRIPTION
**Pull request by yonaskolb**
This updates Spectre to the recent 0.10.0 release. Without this packages that use both PathKit and Spectre can't update Spectre, and therefore are broken in Xcode 12.5

### CODE REVIEW

**Comment by yonaskolb** [comment]
Thanks for the merge @kylef. Whenever you get a chance a new release would be great, so this is Xcode 12.5 compatible. Appreciate your work here.

**Comment by kylef** [comment]
@yonaskolb have you tested this works in Xcode 12.5? I've seen some compilation failures locally with Swift 5.3 `error: ambiguous use of 'expect'` which also occur to on master so not introduced by this PR but likely just a change in Swift.

Just want to make sure that if this was released, it will work for you.

```
$ swift test
/home/kyle/Projects/kylef/PathKit/Tests/PathKitTests/PathKitSpec.swift:293:11: error: ambiguous use of 'expect'
      try expect {
          ^
...
```

**Comment by yonaskolb** [comment]
@kylef, I hadn't tested PathKit on Xcode 12.5, but now that I do I see the same error. It seems Swift can't disambiguate between these 2 functions in Spectre. Is the bottom version required?

```swift
public func expect<T>( _ expression: @autoclosure @escaping () throws -> T?, file: String = #file, line: Int = #line, function: String = #function) -> Expectation<T> {
  return Expectation(file: file, line: line, function: function, expression: expression)
}

public func expect<T>(_ file: String = #file, line: Int = #line, function: String = #function, expression: @escaping () throws -> T?)  -> Expectation<T> {
  return Expectation(file: file, line: line, function: function, expression: expression)
}
```

**Comment by chrisballinger** [comment]
@yonaskolb Here's a fix for that: https://github.com/kylef/PathKit/pull/80/commits/5c3fcb44ac6ec4346059d6326f0cdcb09cf33df9
